[book]
authors = ["Azur冰弦"]
language = "zh-CN"
multilingual = false
src = "src"
title = "ObjectDetectionLab"

[preprocessor.bib]
zotero-uid = "14320567"
cite-hb-tpl = "templates/cite.hbs"
hb-tpl = "templates/ref.hbs"